#!/usr/bin/env bash
# =============================================================================
# AI API Proxy Platform — AWS One-Click Deploy
# Tested on: Ubuntu 22.04 / 24.04  |  Architecture: x86_64 / arm64
#
# Usage (fresh server):
#   curl -fsSL https://raw.githubusercontent.com/Sam-Lee-git/api_hub/master/deploy/deploy-aws.sh | sudo bash
#
# Or after cloning:
#   sudo bash deploy/deploy-aws.sh
#
# Re-run to update (pulls latest code, rebuilds, restarts services).
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }
step()  { echo -e "\n${BOLD}──── $* ────${NC}"; }

[[ $EUID -ne 0 ]] && die "Run as root: sudo bash $0"

# ── Constants ────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/Sam-Lee-git/api_hub.git"
INSTALL_DIR="/opt/ai-proxy"
DATA_DIR="/opt/ai-proxy/data"
GO_VERSION="1.22.4"
NODE_VERSION="22"
APP_USER="aiproxy"

# ── Detect architecture ──────────────────────────────────────────────────────
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  GOARCH="amd64"  ;;
  aarch64) GOARCH="arm64"  ;;
  *) die "Unsupported architecture: $ARCH" ;;
esac

# ── Detect public IP (EC2 metadata, fallback to ifconfig) ───────────────────
PUBLIC_IP=$(curl -sf --max-time 2 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null \
            || curl -sf --max-time 5 https://api.ipify.org 2>/dev/null \
            || hostname -I | awk '{print $1}')

# ── Check if this is an update run ──────────────────────────────────────────
IS_UPDATE=0
[[ -f "$INSTALL_DIR/.env" ]] && IS_UPDATE=1

# =============================================================================
# 1. Collect configuration (skip on update)
# =============================================================================
step "Configuration"

if [[ $IS_UPDATE -eq 0 ]]; then
  echo -e "Detected public IP: ${CYAN}${PUBLIC_IP}${NC}"
  echo ""

  read -rp "Domain name (e.g. api.example.com — leave blank to use IP ${PUBLIC_IP}): " DOMAIN
  read -rp "Admin email [admin@example.com]: " ADMIN_EMAIL
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
  read -rsp "Admin password (min 12 chars): " ADMIN_PASSWORD; echo
  [[ ${#ADMIN_PASSWORD} -lt 12 ]] && die "Admin password must be at least 12 characters"

  echo ""
  echo "─── AI Provider API Keys (leave blank to configure later in $INSTALL_DIR/.env) ───"
  read -rp "OpenAI API key (sk-...): "        OPENAI_API_KEY
  read -rp "Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY
  read -rp "Google API key (AIza...): "       GOOGLE_API_KEY
  read -rp "Alibaba/Qwen API key: "           ALIBABA_API_KEY

  echo ""
  echo "─── Payment (leave blank, fill in $INSTALL_DIR/.env later) ───────────────────"
  read -rp "Alipay App ID: "  ALIPAY_APP_ID
  read -rp "WeChat Mch ID: "  WECHAT_MCH_ID
  read -rp "WeChat App ID: "  WECHAT_APP_ID

  # Auto-generate secrets
  JWT_ACCESS_SECRET=$(openssl rand -hex 32)
  JWT_REFRESH_SECRET=$(openssl rand -hex 32)
  WECHAT_API_V3_KEY=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

  NOTIFY_HOST="${DOMAIN:-$PUBLIC_IP}"

  mkdir -p "$DATA_DIR"
  cat > "$INSTALL_DIR/.env" <<ENV
# Generated by deploy-aws.sh — edit freely
DB_DRIVER=sqlite
SQLITE_PATH=${DATA_DIR}/aiproxy.db
CACHE_DRIVER=memory

JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
GOOGLE_API_KEY=${GOOGLE_API_KEY}
ALIBABA_API_KEY=${ALIBABA_API_KEY}

ALIPAY_APP_ID=${ALIPAY_APP_ID}
ALIPAY_PRIVATE_KEY=
ALIPAY_PUBLIC_KEY=
ALIPAY_NOTIFY_URL=https://${NOTIFY_HOST}/api/payment/alipay/notify

WECHAT_MCH_ID=${WECHAT_MCH_ID}
WECHAT_APP_ID=${WECHAT_APP_ID}
WECHAT_API_V3_KEY=${WECHAT_API_V3_KEY}
WECHAT_CERT_SERIAL=
WECHAT_NOTIFY_URL=https://${NOTIFY_HOST}/api/payment/wechat/notify

ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

PORT=8080
ENV=production
ENV
  chmod 600 "$INSTALL_DIR/.env"
  ok ".env written to $INSTALL_DIR/.env"
else
  ok "Update mode — reusing existing $INSTALL_DIR/.env"
  source "$INSTALL_DIR/.env" 2>/dev/null || true
  DOMAIN="${DOMAIN:-}"
fi

# =============================================================================
# 2. System packages
# =============================================================================
step "System packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
for pkg in git curl wget build-essential openssl nginx certbot python3-certbot-nginx; do
  dpkg -s "$pkg" &>/dev/null || apt-get install -y -qq "$pkg"
done
ok "Base packages ready"

# =============================================================================
# 3. Go
# =============================================================================
step "Go ${GO_VERSION}"
if ! command -v go &>/dev/null || [[ "$(go version 2>/dev/null | awk '{print $3}')" != "go${GO_VERSION}" ]]; then
  wget -q "https://go.dev/dl/go${GO_VERSION}.linux-${GOARCH}.tar.gz" -O /tmp/go.tar.gz
  rm -rf /usr/local/go
  tar -C /usr/local -xzf /tmp/go.tar.gz
  rm /tmp/go.tar.gz
  ln -sf /usr/local/go/bin/go    /usr/local/bin/go
  ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt
  ok "Go installed: $(go version)"
else
  ok "Go already present: $(go version)"
fi
export PATH=$PATH:/usr/local/go/bin

# =============================================================================
# 4. Node.js
# =============================================================================
step "Node.js ${NODE_VERSION}"
if ! command -v node &>/dev/null || [[ "$(node -v | cut -dv -f2 | cut -d. -f1)" -lt $NODE_VERSION ]]; then
  curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - >/dev/null
  apt-get install -y -qq nodejs
  ok "Node.js installed: $(node -v)"
else
  ok "Node.js already present: $(node -v)"
fi

# =============================================================================
# 5. Clone or update repository
# =============================================================================
step "Source code"
REPO_DIR="$INSTALL_DIR/src"

if [[ -d "$REPO_DIR/.git" ]]; then
  info "Pulling latest changes..."
  git -C "$REPO_DIR" pull --ff-only
  ok "Repository updated"
else
  info "Cloning $REPO_URL..."
  mkdir -p "$INSTALL_DIR"
  git clone --depth=1 "$REPO_URL" "$REPO_DIR"
  ok "Repository cloned"
fi

# Symlink .env into the repo root so viper finds it
ln -sf "$INSTALL_DIR/.env" "$REPO_DIR/backend/.env"

# =============================================================================
# 6. Build backend
# =============================================================================
step "Build backend"
cd "$REPO_DIR/backend"
go mod tidy
go build -ldflags="-s -w" -o "$INSTALL_DIR/backend" ./cmd/server/main.go
ok "Backend binary built → $INSTALL_DIR/backend"

# =============================================================================
# 7. Build frontend
# =============================================================================
step "Build frontend"
cd "$REPO_DIR/frontend"
npm ci --silent
npm run build

STANDALONE="$REPO_DIR/frontend/.next/standalone"
FRONTEND_DEST="$INSTALL_DIR/frontend"

rm -rf "$FRONTEND_DEST"
cp -r  "$STANDALONE"                           "$FRONTEND_DEST"
cp -r  "$REPO_DIR/frontend/.next/static"       "$FRONTEND_DEST/.next/static"
cp -r  "$REPO_DIR/frontend/public"             "$FRONTEND_DEST/public"
ok "Frontend built → $FRONTEND_DEST"

# =============================================================================
# 8. Create system user
# =============================================================================
step "System user"
id -u "$APP_USER" &>/dev/null || useradd -r -s /bin/false "$APP_USER"
chown -R "$APP_USER:$APP_USER" "$INSTALL_DIR"
ok "User $APP_USER ready"

# =============================================================================
# 9. systemd — backend
# =============================================================================
step "systemd services"
cat > /etc/systemd/system/ai-proxy-backend.service <<UNIT
[Unit]
Description=AI Proxy Platform — Backend
After=network.target

[Service]
Type=simple
User=${APP_USER}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=${INSTALL_DIR}/backend
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

# systemd — frontend
cat > /etc/systemd/system/ai-proxy-frontend.service <<UNIT
[Unit]
Description=AI Proxy Platform — Frontend
After=network.target

[Service]
Type=simple
User=${APP_USER}
WorkingDirectory=${INSTALL_DIR}/frontend
Environment=NODE_ENV=production
Environment=PORT=3000
Environment=HOSTNAME=127.0.0.1
ExecStart=/usr/bin/node server.js
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now ai-proxy-backend
systemctl enable --now ai-proxy-frontend
sleep 2
systemctl restart ai-proxy-backend ai-proxy-frontend
ok "Services started"

# =============================================================================
# 10. Nginx
# =============================================================================
step "Nginx"
SERVER_NAME="${DOMAIN:-_}"
cat > /etc/nginx/sites-available/ai-proxy <<NGINX
upstream backend  { server 127.0.0.1:8080; keepalive 32; }
upstream frontend { server 127.0.0.1:3000; keepalive 32; }

server {
    listen 80;
    server_name ${SERVER_NAME};

    # Required for SSE / streaming — must NOT buffer
    proxy_buffering        off;
    proxy_cache            off;
    proxy_read_timeout     330s;
    proxy_send_timeout     330s;
    proxy_connect_timeout  10s;
    proxy_http_version     1.1;

    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Connection        "";

    # Backend routes
    location ~ ^/(api|v1|health)/ {
        proxy_pass http://backend;
    }

    # Frontend
    location / {
        proxy_pass http://frontend;
        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
NGINX

ln -sf /etc/nginx/sites-available/ai-proxy /etc/nginx/sites-enabled/ai-proxy
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
ok "Nginx configured"

# =============================================================================
# 11. SSL (optional, only if a real domain was provided)
# =============================================================================
if [[ -n "${DOMAIN:-}" ]]; then
  step "SSL — Let's Encrypt"
  read -rp "Issue SSL certificate for $DOMAIN? [y/N]: " SSL_YN
  if [[ "${SSL_YN,,}" == "y" ]]; then
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
      -m "${ADMIN_EMAIL:-admin@example.com}" --redirect
    ok "SSL certificate issued and Nginx updated"
  fi
fi

# =============================================================================
# 12. Health check
# =============================================================================
step "Health check"
sleep 3

BACKEND_OK=0
FRONTEND_OK=0

curl -sf http://127.0.0.1:8080/health >/dev/null 2>&1 && BACKEND_OK=1
HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" http://127.0.0.1:3000 2>/dev/null || echo "000")
[[ "$HTTP_CODE" =~ ^2 ]] && FRONTEND_OK=1

BASE_URL="http://${DOMAIN:-$PUBLIC_IP}"

echo ""
echo -e "${BOLD}════════════════════════════════════════${NC}"
echo -e "${BOLD}   Deployment Complete${NC}"
echo -e "${BOLD}════════════════════════════════════════${NC}"
echo ""

[[ $BACKEND_OK -eq 1 ]] \
  && ok  "Backend  :8080  ✓" \
  || warn "Backend  :8080  FAILED  →  journalctl -u ai-proxy-backend -n 50"

[[ $FRONTEND_OK -eq 1 ]] \
  && ok  "Frontend :3000  ✓" \
  || warn "Frontend :3000  HTTP $HTTP_CODE  →  journalctl -u ai-proxy-frontend -n 50"

echo ""
echo -e "  User portal  : ${GREEN}${BASE_URL}${NC}"
echo -e "  Admin panel  : ${GREEN}${BASE_URL}/admin/dashboard${NC}"
echo -e "  API endpoint : ${GREEN}${BASE_URL}/v1/chat/completions${NC}"
echo ""
echo -e "  Config file  : ${CYAN}${INSTALL_DIR}/.env${NC}"
echo -e "  SQLite DB    : ${CYAN}${DATA_DIR}/aiproxy.db${NC}"
echo -e "  Source code  : ${CYAN}${REPO_DIR}${NC}"
echo ""
echo "  Useful commands:"
echo "    journalctl -fu ai-proxy-backend    # live backend logs"
echo "    journalctl -fu ai-proxy-frontend   # live frontend logs"
echo "    systemctl restart ai-proxy-backend # restart backend"
echo "    sudo bash $0                       # re-run to update"
echo ""

if [[ -n "${DOMAIN:-}" ]]; then
  echo -e "  ${YELLOW}Remember: point your DNS A record for ${DOMAIN} → ${PUBLIC_IP}${NC}"
  echo -e "  ${YELLOW}and open ports 80/443 in your EC2 Security Group.${NC}"
else
  echo -e "  ${YELLOW}Open ports 80 and 8080 in your EC2 Security Group if not already done.${NC}"
fi
echo ""
ok "Done."
